# Generated by Django 5.2 on 2026-01-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_type', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('unit_of_measure', models.CharField(max_length=10)),
                ('standard_cost', models.FloatField()),
                ('list_price', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('origin_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('trade_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('trade_value', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('trade_status', models.CharField(max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_trades', to='trading.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_trades', to='trading.customer')),
            ],
        ),
    ]
