# Generated by Django 5.2 on 2026-01-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trade_date',
        ),
    ]
